authors = ["Yutaka Masuda <yutaka@uga.edu>"]
name = "SparseMatrixDicts"
uuid = "5cb6c4b0-9b79-11e8-24c9-f9621d252589"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
